---
- hosts: all
  sudo: yes
  gather_facts: False
  tasks:
  - service: name=puppet state=stopped
  - lineinfile: dest=/etc/security/access.conf regexp="\+:{{ item }}:ALL" line="+:{{ item }}:ALL" insertafter=BOF
    with_items:
      - ssekiguchi
      - jsharps
      - gsato
      - yhata
      - ytakahashi
  - lineinfile: dest=/etc/ssh/sshd_config  regexp="PasswordAuthentication" line="PasswordAuthentication yes"
  - service: name=sshd state=restarted
