---
#- name: Check if Apache is running
#  become: yes
#  hosts: '{{host | default("all") }}'
#  shell: service httpd status 
#  ignore_errors: yes
# changed_when: false
# register: service_apache_status
- name: checking if http is running
  become: yes 
  hosts: '{{host | default("all") }}'
  command: service httpd status
  ignore_errors: no
  changed_when: false
  register: service_httpd_status
 
#- name: Check on noc boxes
#  become : no
#  gather_facts: no
#  hosts: '{{ host | default("all") }}'
#  tasks:
#    - name: Checking if the stack is reachable
#      action: ping
#      tags:
#        - ping

#- name: check on motd file 
#  become : yes 
#  gather_facts: no 
#  hosts: '{{host | default("all") }}'
#
#  vars:
#     contents: "{{ lookup('file', '/etc/motd') }}"
#  tasks:
#     - debug: msg="the value of motd is {{ contents }}"
#
#
